version: '3'
services:
  api:
    build:
      context: ./api
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb+srv://walidrifaii53:Lnb8tP90S06lhF8D@cluster0.5uov0.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"